In [7]:
import numpy as np
import pandas as pd

import json

In [2]:
with open("models/results.json", "r") as f:
    results = json.load(f)

In [12]:
table = []
for result in results:
    rf, xgb = {}, {}
    rf["id"] = result["id"] + "_rf"
    xgb["id"] = result["id"] + "_xgb"
    rf_predict = (np.array(result["y_proba_rf"]) >= 0.5).astype(int)
    xgb_predict = (np.array(result["y_proba_xgb"]) >= 0.5).astype(int)
    rf["accuracy"] = np.mean(np.array(result["y_test"]) == rf_predict)
    xgb["accuracy"] = np.mean(np.array(result["y_test"]) == xgb_predict)
    table.append(rf)
    table.append(xgb)

[{'id': 'match_12_15_rf', 'accuracy': 0.8173076923076923},
 {'id': 'match_12_15_xgb', 'accuracy': 0.8125},
 {'id': 'frame_12_15_rf', 'accuracy': 0.7704326923076923},
 {'id': 'frame_12_15_xgb', 'accuracy': 0.7836538461538461},
 {'id': 'match_8_15_rf', 'accuracy': 0.8293269230769231},
 {'id': 'match_8_15_xgb', 'accuracy': 0.8149038461538461},
 {'id': 'match_8_12_15_rf', 'accuracy': 0.8197115384615384},
 {'id': 'match_8_12_15_xgb', 'accuracy': 0.8028846153846154},
 {'id': 'match_15_rf', 'accuracy': 0.8413461538461539},
 {'id': 'match_15_xgb', 'accuracy': 0.8076923076923077}]

In [15]:
df = pd.DataFrame(table)
df.sort_values("accuracy", ascending=False)

                  id  accuracy
8        match_15_rf  0.841346
4      match_8_15_rf  0.829327
6   match_8_12_15_rf  0.819712
0     match_12_15_rf  0.817308
5     match_8_15_xgb  0.814904
1    match_12_15_xgb  0.812500
9       match_15_xgb  0.807692
7  match_8_12_15_xgb  0.802885
3    frame_12_15_xgb  0.783654
2     frame_12_15_rf  0.770433

In [25]:
target = results[4]
pd.DataFrame({"feature":target["features"],"importance":target["importances_rf"]}).sort_values("importance", ascending=False)

                         feature  importance
12                   totalGold_1    0.072280
32                   totalGold_3    0.058681
42                   totalGold_4    0.052952
22                   totalGold_2    0.049910
13                          xp_1    0.039903
33                          xp_3    0.039861
23                          xp_2    0.037428
43                          xp_4    0.036201
3                           xp_0    0.033869
2                    totalGold_0    0.027862
15  totalDamageDoneToChampions_1    0.025922
40                       level_4    0.022659
35  totalDamageDoneToChampions_3    0.020160
4              totalDamageDone_0    0.018468
34             totalDamageDone_3    0.018038
25  totalDamageDoneToChampions_2    0.017018
46            totalDamageTaken_4    0.015755
48              goldPorportion_4    0.015731
18              goldPorportion_1    0.015275
28              goldPorportion_2    0.015241
10                       level_1    0.014954
14             totalDamageDone_1    0.014603
45  totalDamageDoneToChampions_4    0.014343
7                   creepScore_0    0.014182
30                       level_3    0.014085
24             totalDamageDone_2    0.013505
38              goldPorportion_3    0.013467
9                 xpPorportion_0    0.013418
39                xpPorportion_3    0.012898
26            totalDamageTaken_2    0.012835
0                        level_0    0.012814
44             totalDamageDone_4    0.012390
37                  creepScore_3    0.012386
29                xpPorportion_2    0.012263
20                       level_2    0.012146
8               goldPorportion_0    0.012054
21    timeEnemySpentControlled_2    0.012043
19                xpPorportion_1    0.012013
1     timeEnemySpentControlled_0    0.011924
49                xpPorportion_4    0.011871
36            totalDamageTaken_3    0.011830
16            totalDamageTaken_1    0.011179
41    timeEnemySpentControlled_4    0.011159
31    timeEnemySpentControlled_3    0.010660
6             totalDamageTaken_0    0.010631
17                  creepScore_1    0.010548
27                  creepScore_2    0.010491
5   totalDamageDoneToChampions_0    0.010261
47                  creepScore_4    0.010010
11    timeEnemySpentControlled_1    0.009826

In [22]:
target = results[2]
pd.DataFrame({"feature":target["features"],"importance":target["importances_rf"]}).sort_values("importance", ascending=False).head(10)

                feature  importance
63         xp_1_frame15    0.061528
92  totalGold_4_frame15    0.060910
72  totalGold_2_frame15    0.057345
93         xp_4_frame15    0.056981
82  totalGold_3_frame15    0.055558
62  totalGold_1_frame15    0.042915
80      level_3_frame15    0.041515
90      level_4_frame15    0.038340
60      level_1_frame15    0.034894
83         xp_3_frame15    0.034574

In [23]:
target = results[2]
pd.DataFrame({"feature":target["features"],"importance":target["importances_xgb"]}).sort_values("importance", ascending=False).head(10)

                feature  importance
93         xp_4_frame15    0.058806
80      level_3_frame15    0.043206
83         xp_3_frame15    0.036878
72  totalGold_2_frame15    0.034382
62  totalGold_1_frame15    0.031581
12   totalGold_1_frame8    0.030548
53         xp_0_frame15    0.023468
63         xp_1_frame15    0.022814
52  totalGold_0_frame15    0.019783
42   totalGold_4_frame8    0.019579